baseURL = 'https://teukuanca.com/'
languageCode = 'id-id'
title = 'teukuanca.com'
theme = 'mainroad'

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Situs Web Resmi teukuanca.com"
  author = "Teuku Anca"
  subtitle = "Portal Artikel dan Berita"


