# Force rebuild 2026-09-25
baseURL = 'https://teukuanca.com/'
languageCode = 'id-id'
title = 'teukuanca.com'
theme = 'PaperMod'
googleAnalytics = "G-B4RNLBDNYC"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  env = "production"
  description = "Situs Web Resmi teukuanca.com"
  author = "Teuku Anca"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  comments = true
  ShowSearchIcon = true

  [params.header]
    stickyMenu = true

  [params.assets]
    disableHLJS = true
    favicon = "/images/logo.webp"
    favicon16x16 = "/images/logo.webp"
    favicon32x32 = "/images/logo.webp"

    [params.homeInfoParams]
    Title = ""
    Content = ""

  [params.utterances]
    repo = "teukuanca-creat/situsku"
    issueTerm = "pathname"
    theme = "github-light"
    label = ""

  [params.analytics]
    google.SiteVerificationTag = ""

  [params.verification]
    bing = "90402F60B1603D31F7A14C9E4C1A0E47"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/share/14qwMpLdrqS/"
  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/teukuanca_TJI"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/ancateuku"
  [[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com/@teukuancat.j.i8389"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "search"
    name = ""
    url = "/search/"
    weight = 5
    pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"></circle><path d="m21 21-4.35-4.35"></path></svg>'
  [[menu.main]]
    identifier = "categories"
    name = "Kategori"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tag"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "Tentang Saya"
    url = "/pages/tentang-saya/"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "Hubungi Saya"
    url = "/pages/hubungi-saya/"
    weight = 40
  [[menu.footer]]
    identifier = "disclaimer"
    name = "Disclaimer"
    url = "/pages/disclaimer/"
    weight = 10
  [[menu.footer]]
    identifier = "privacy"
    name = "Kebijakan Privasi"
    url = "/pages/kebijakan-privasi/"
    weight = 20
  [[menu.footer]]
    identifier = "syarat"
    name = "Syarat & Ketentuan"
    url = "/pages/syarat-dan-ketentuan/"
    weight = 30
  [[menu.footer]]
    identifier = "tentang"
    name = "Tentang Saya"
    url = "/pages/tentang-saya/"
    weight = 40
  [[menu.footer]]
    identifier = "kontak"
    name = "Hubungi Saya"
    url = "/pages/hubungi-saya/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
